apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: mariadb-benchmark

resources:
- benchmarks/overlays/mariadb-local
- benchmarks/overlays/mariadb-pv
- secrets/mariadb-creds.yaml
- console
