apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -pv
commonLabels:
  component: mariadb-pv

resources:
- ../../base
- pvcs/mariadb-data.yaml

patches:
  - path: deployments/mariadb_patch.yaml
