apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -local
commonLabels:
  component: mariadb-local

resources:
- ../../base

patches:
  - path: deployments/mariadb_patch.yaml
