apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: console

resources:
- deployments/console.yaml
- routes/console.yaml
- services/console.yaml

configMapGenerator:
  - name: console-scripts
    files:
      - scripts/console.py
      - scripts/index.j2.html
      - scripts/requirements.txt
      - scripts/run-console.sh
      - scripts/updateresults.js
