apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: perf-as-root
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: run-as-root
subjects:
  - kind: ServiceAccount
    name: perf
