apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: run-as-root
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - anyuid
    verbs:
      - use
